# Generated by Django 4.2.4 on 2025-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='fee',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fromAccount',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='toAccount',
            field=models.CharField(max_length=80),
        ),
    ]
