"""
Django settings for insecure banking project.

Generated by 'django-admin startproject' using Django 4.2.4.

WARNING: This project contains intentional security vulnerabilities for
educational purposes. These settings should never be used in production.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This is intentionally weak for educational purposes
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-u5+_1cyk&@5&#ik_qn09f#v4m^c^9riq68xnd@3uwofv$wi)3_")

# SECURITY WARNING: don't run with debug turned on in production!
# This setting allows detailed error pages with sensitive information
DEBUG = os.environ.get("DEBUG", "True") == "True"

# SECURITY WARNING: In production, restrict ALLOWED_HOSTS to specific domains
# Using '*' allows any host, which is a security risk
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# Application definition
# These are the Django applications that make up this project

INSTALLED_APPS = [
    "django.contrib.admin",  # Django admin interface
    "django.contrib.auth",  # Authentication framework
    "django.contrib.contenttypes",  # Content type system
    "django.contrib.sessions",  # Session framework
    "django.contrib.messages",  # Messaging framework
    "django.contrib.staticfiles",  # Static file management
    "web",  # Our banking application
]

# Middleware classes that process requests and responses
# Order matters - they are applied in sequence

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Note: CSRF middleware intentionally omitted for educational purposes
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.AuthRequiredMiddleware",  # Custom authentication middleware
]

# Root URL configuration module
ROOT_URLCONF = "config.urls"

# Template configuration
# Defines how Django finds and renders templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "src" / "web"],  # Additional template directories
        "APP_DIRS": True,  # Look for templates in app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "web.context_processors.version_info",  # Custom context processor
            ],
        },
    },
]

# WSGI application
WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Using SQLite for simplicity - not recommended for production

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# Intentionally disabled for educational purposes

AUTH_PASSWORD_VALIDATORS = []

# Custom authentication backend
# WARNING: This uses insecure authentication for educational purposes
AUTHENTICATION_BACKENDS = ["web.services.AccountService"]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# URL behavior
# Do not append slash - requires exact URL matches
APPEND_SLASH = False
